/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as PlayerTypeIdRouteImport } from './routes/player.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerTypeIdRoute = PlayerTypeIdRouteImport.update({
  id: '/player/$type/$id',
  path: '/player/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/loading': typeof LoadingRoute
  '/movies': typeof MoviesRoute
  '/playlist': typeof PlaylistRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/api/stream': typeof ApiStreamRoute
  '/player/$type/$id': typeof PlayerTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/loading': typeof LoadingRoute
  '/movies': typeof MoviesRoute
  '/playlist': typeof PlaylistRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/api/stream': typeof ApiStreamRoute
  '/player/$type/$id': typeof PlayerTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/guide': typeof GuideRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/loading': typeof LoadingRoute
  '/movies': typeof MoviesRoute
  '/playlist': typeof PlaylistRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/api/stream': typeof ApiStreamRoute
  '/player/$type/$id': typeof PlayerTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/guide'
    | '/history'
    | '/home'
    | '/live'
    | '/loading'
    | '/movies'
    | '/playlist'
    | '/series'
    | '/settings'
    | '/api/stream'
    | '/player/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/guide'
    | '/history'
    | '/home'
    | '/live'
    | '/loading'
    | '/movies'
    | '/playlist'
    | '/series'
    | '/settings'
    | '/api/stream'
    | '/player/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/guide'
    | '/history'
    | '/home'
    | '/live'
    | '/loading'
    | '/movies'
    | '/playlist'
    | '/series'
    | '/settings'
    | '/api/stream'
    | '/player/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  GuideRoute: typeof GuideRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LiveRoute: typeof LiveRoute
  LoadingRoute: typeof LoadingRoute
  MoviesRoute: typeof MoviesRoute
  PlaylistRoute: typeof PlaylistRoute
  SeriesRoute: typeof SeriesRoute
  SettingsRoute: typeof SettingsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  PlayerTypeIdRoute: typeof PlayerTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$type/$id': {
      id: '/player/$type/$id'
      path: '/player/$type/$id'
      fullPath: '/player/$type/$id'
      preLoaderRoute: typeof PlayerTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  GuideRoute: GuideRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LiveRoute: LiveRoute,
  LoadingRoute: LoadingRoute,
  MoviesRoute: MoviesRoute,
  PlaylistRoute: PlaylistRoute,
  SeriesRoute: SeriesRoute,
  SettingsRoute: SettingsRoute,
  ApiStreamRoute: ApiStreamRoute,
  PlayerTypeIdRoute: PlayerTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
